#!/bin/sh
set -e

# -t 2419200 = 4 weeks TTL

varnishd \
  -f /etc/varnish/default.vcl \
  -a http=:80,HTTP \
  -s malloc,$VARNISH_SIZE \
  -t 2419200 \
  -p default_ttl=2419200
     
varnishadm param.set default_ttl 2419200.000

/usr/bin/varnishncsa \
  -b -c \
  -F '%{Host}i %h %l %u %t \"%r\" %s %b \"%{Referer}i\" \"%{User-agent}i\" \"%{Varnish:hitmiss}x\"'
